### ISSUE TITLE
Integration to Sanity

### ISSUE THREAD

**Issue by Pillin** [JSConfCL/2024#18]
## Descripción
Para la administración de contenido es necesario el poder integrar un CMS,  el cual mantenga todo los textos y la distribución de las componentes

## Criteria de Aceptación
- [ ] Integrarse con la página vía GraphQL
- [ ] Al menos tiene que estar el home migrado a Sanity.

**Comment by geekhadev** [comment]
He creado un PR para tratar de atender este ISSUE, espero revisión y si puedo mejorar recibir el feedback, gracias.

**Comment by geekhadev** [comment]
Avances de esta actividad en PR #40 @joseglego

**Comment by geekhadev** [comment]
Análisis de la estructura de datos, 2024-04-17

![Image](https://github.com/JSConfCL/2024/assets/499907/c553d2a9-6468-4a8d-b1f8-a13e87c937a6)
